import {
  Beef,
  Beer,
  Cake,
  CakeSlice,
  Candy,
  Cherry,
  Citrus,
  Coffee,
  Cookie,
  CookingPot,
  Croissant,
  CupSoda,
  Donut,
  Drumstick,
  EggFried,
  Fish,
  Flame,
  GlassWater,
  Ham,
  Hamburger,
  IceCreamBowl,
  IceCreamCone,
  Leaf,
  Martini,
  Package,
  Pizza,
  Popcorn,
  Popsicle,
  Salad,
  Sandwich,
  Shrimp,
  Soup,
  Store,
  UtensilsCrossed,
  Wheat,
  Wine,
  type LucideIcon,
} from "lucide-react";

// Ícones que o admin pode escolher para as categorias da plataforma. O banco
// guarda só o nome; aqui ele vira o desenho.
export const CATEGORY_ICONS: Record<string, { icon: LucideIcon; label: string }> = {
  sandwich: { icon: Sandwich, label: "Lanche" },
  pizza: { icon: Pizza, label: "Pizza" },
  "cup-soda": { icon: CupSoda, label: "Bebida" },
  drumstick: { icon: Drumstick, label: "Frango / porção" },
  "cake-slice": { icon: CakeSlice, label: "Bolo / sobremesa" },
  soup: { icon: Soup, label: "Prato de comida" },
  package: { icon: Package, label: "Marmita / embalagem" },
  fish: { icon: Fish, label: "Peixe / japonesa" },
  "ice-cream-bowl": { icon: IceCreamBowl, label: "Açaí / tigela" },
  "ice-cream-cone": { icon: IceCreamCone, label: "Sorvete" },
  "utensils-crossed": { icon: UtensilsCrossed, label: "Talheres" },
  beef: { icon: Beef, label: "Carne / churrasco" },
  salad: { icon: Salad, label: "Salada / saudável" },
  coffee: { icon: Coffee, label: "Café" },
  croissant: { icon: Croissant, label: "Padaria" },
  beer: { icon: Beer, label: "Cerveja" },
  wine: { icon: Wine, label: "Vinho" },
  cookie: { icon: Cookie, label: "Doce / biscoito" },
  "egg-fried": { icon: EggFried, label: "Café da manhã" },
  ham: { icon: Ham, label: "Frios" },
  popcorn: { icon: Popcorn, label: "Petisco" },
  hamburger: { icon: Hamburger, label: "Hambúrguer" },
  wheat: { icon: Wheat, label: "Massas / trigo" },
  "cooking-pot": { icon: CookingPot, label: "Panela / forno" },
  martini: { icon: Martini, label: "Drinks" },
  "glass-water": { icon: GlassWater, label: "Sucos / água" },
  citrus: { icon: Citrus, label: "Frutas / sucos" },
  flame: { icon: Flame, label: "Brasa / espetinho" },
  shrimp: { icon: Shrimp, label: "Frutos do mar" },
  leaf: { icon: Leaf, label: "Regional / natural" },
  cake: { icon: Cake, label: "Bolos" },
  donut: { icon: Donut, label: "Doces / confeitaria" },
  candy: { icon: Candy, label: "Balas / doces" },
  cherry: { icon: Cherry, label: "Frutas" },
  popsicle: { icon: Popsicle, label: "Picolé" },
};

export function CategoryIcon({ name, className }: { name: string | null | undefined; className?: string }) {
  const Icon = (name && CATEGORY_ICONS[name]?.icon) || Store;
  return <Icon className={className} aria-hidden="true" />;
}
